grant-type:
    password: password
    refresh_token: refresh_token
security:
    oauth2:
        client:
            client-id: skilltrackerClient
            client-secret: skilltrackerSecret
            refresh-token-validity-seconds: 1500
            signing-key: skilltrackerSigningKey
            token-validity-seconds: 300
server:
    port: 5002
spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: skillTracker
